sample_payload: 'sample_payload.json'
OUTPUT_DIRECTORY : "./outputs/"
DATA_DIR : "./data/"
MODEL_DIRECTORY : "./models/"
IMAGEDATA_DIR : "./data/"
LABEL_DIRECTORY : "./data/"
WEIGHTS_DIR : "./models"
exp_name: "Mnist"



### TRAIN FUNCTION ARGS ###
train_epochs : 5
NUM_INPUT : 784
RAW_IMG_SIZE : (28, 28)
IMG_SIZE : (28, 28)
INPUT_SHAPE : (IMG_SIZE[0], IMG_SIZE[1])
NUM_STEPS: 1000
MAX_EPOCH : 2
BATCH_SIZE: 128
FOLDS : [1]
DISPLAY_STEP: 100
STOPPING_PATIENCE : 32
LR_PATIENCE : 16
INITIAL_LR : 0.1
NUM_CLASSES : 10
CLASSES : [0, 1, 2, 3, 4, 5, 6, 7, 8,9]
CLASSES_STR : ['0', '1', '2', '3', '4', '5', '6', '7','8','9']
MODELNAME: resnet                                                               #### support for [resnet, inception]
