sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "text-classification"

### TRAIN FUNCTION ARGS ###
train_epochs: 1
batch_size: 8
N_GRAMS: 2
EMBED_DIM: 32
