sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
IMG_DIRECTORY : "/home/ubuntu/Home/AlectioSDK/examples/image_classification/Deepweeds/data/images/"
LABEL_DIRECTORY : "/home/ubuntu/Home/AlectioSDK/examples/image_classification/Deepweeds/data/labels/"
exp_name: "Deepweeds"
weightsclear: True
CKPT_EXT : '.pkl'



### TRAIN FUNCTION ARGS ###
batch_size: 8
RAW_IMG_SIZE : [256, 256]
IMG_SIZE : [224, 224]
INPUT_SHAPE : [224, 224, 3]
MAX_EPOCH : 15
BATCH_SIZE: 32
FOLDS : [1]
STOPPING_PATIENCE : 32
LR_PATIENCE : 16
INITIAL_LR : 0.0001
CLASSES : [0, 1, 2, 3, 4, 5, 6, 7, 8]
CLASSES_STR : ['0', '1', '2', '3', '4', '5', '6', '7','8']
MODELNAME: resnet                                                      #### support for [resnet, inception]
